# 신경망 만들기

Step 1. 기본 클래스 만들기

- 구조 정의
- 학습
- 추론

In [23]:
import numpy as np
import scipy.special

In [50]:
# 생성자때 최대한 많은 정보 넣어주는게 좋다.
# 학습률 : hyper parameter(개발이 진행되면서 추가한 파라미터)
# parameter와 hyper parameter의 차이점이 면접질문
# weight 값에 매칭된 data => parameter

class MyNeuralNet:
    def __init__(self, inputnodes, hiddennodes, outputnodes, learningrate):
        
        # 입력, 은닉, 출력 계층의 노드 개수 설정
        self.innode = inputnodes
        self.hnode = hiddennodes
        self.outnode = outputnodes
        
        # 학습률
        self.lr = learningrate
        
        # (열 갯수, 행 갯수)
        self.wih = np.random.rand(self.hnode, self.innode) - 0.5
        self.who = np.random.rand(self.outnode, self.hnode) - 0.5
        
        #pass
    
    def printWeight(self):
        print(self.wih.shape, self.wih)
        print(self.who.shape, self.who)
    
    # forward and backward
    def train(self, input_list, target_list):
        input = np.array(input_list, ndmin=2).T
        
        # input -> hidden
        hidden_input = np.dot(self.wih, input)
        hidden_output = scipy.special.expit(hidden_input)
        
        #hidden -> output
        output_hidden = np.dot(self.who, hidden_output)
        final_outputs = scipy.special.expit(output_hidden)
        
        # Get Error
        targets = np.array(target_list, ndmin=2).T
        
        output_error = targets - final_outputs
        hidden_error = np.dot(self.who.T, output_error)
        print(output_error)
        
        # update weight
        self.who += self.lr * np.dot((output_error * final_outputs) * (1.0 - final_outputs), np.transpose(hidden_output))
        self.wih += self.lr * np.dot((hidden_error * hidden_output) * (1.0 - hidden_output), np.transpose(input))
    
    # forward
    def inference(self, input_list):
        input = np.array(input_list, ndmin=2).T
        
        # input -> hidden
        hidden_input = np.dot(self.wih, input)
        hidden_output = scipy.special.expit(hidden_input)
        
        #hidden -> output
        output_hidden = np.dot(self.who, hidden_output)
        final_output = scipy.special.expit(output_hidden)
        
        return final_output
        

In [53]:
net = MyNeuralNet(4, 4, 3, 0.5)
print(net.inference([10, 10, 20, 20]))
net.train([10, 20, 40, 50], [0.5, 0.2, 0.1])
print(net.inference([10, 10, 20, 20]))

[[0.49995318]
 [0.49990565]
 [0.49987837]]
[[ 1.17808319e-07]
 [-2.99999761e-01]
 [-3.99999711e-01]]
[[0.49995314]
 [0.49990557]
 [0.49987828]]
